app:
  application_port: 8000
  base_url : "http://localhost:8000"
  domain : "localhost"
  is_prod : false
redis_uri: "adasd"
database:
  username: "yollotl"
  password: ""
  port: 5432
  host: "localhost"
  database_name: "juezguapa"
  require_ssl: false
email_client:
  host : "smtp.gmail.com"
  sender: "<sender>"
  authorization_token : "<gmail authorization_token>"
  timeout_milliseconds: 1000
redis:
  uri : "redis://localhost:6379"
  secret : "asdasasdasaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaannnnnnnnnnnnnnnnnnnnn"
rabbitmq:
  uri : "amqp://localhost:5672"
  queue : "submissions"
