name: Build and Publish Web server to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Optional: Enable manual workflow runs
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Web Server 
      uses: actions/checkout@v4
      with:
        repository: Club-de-Algoritmia-Acatlan-GUAPA/web_server
        path: web_server

    - name: Checkout Primitypes
      uses: actions/checkout@v4
      with:
        repository: Club-de-Algoritmia-Acatlan-GUAPA/primitypes
        path: primitypes

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./web_server/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/web_server:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/web_server:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/web_server:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/web_server:buildcache,mode=max
